/**
 * 公開 API リファレンス生成スクリプト。
 *
 * `bun run --cwd website api:generate` で実行され、TypeDoc +
 * typedoc-plugin-markdown で `website/docs/api/` に Markdown を生成する。
 * 生成物はコミットする(Cloudflare のビルドでは実行されない)。
 *
 * 流れ:
 *  1. 各パッケージを個別に TypeDoc で JSON へ変換(typedoc.base.json)
 *     — ルートの package.json は workspaces を持つため "packages"
 *     エントリポイント戦略が使えず、"merge" 戦略で統合する。
 *  2. JSON を統合して Markdown を出力(typedoc.json)
 *  3. Docusaurus の autogenerated サイドバー向けに _category_.json と
 *     frontmatter を後処理で付与する
 */

import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const websiteDir = path.dirname(here);
const repoRoot = path.dirname(websiteDir);
const cacheDir = path.join(here, ".cache");
const outDir = path.join(websiteDir, "docs", "api");

const require = createRequire(import.meta.url);
const typedocBin = path.join(path.dirname(require.resolve("typedoc/package.json")), "bin", "typedoc");

/** ドキュメント対象のパッケージ(掲載順)。 */
const packages = [
	{ id: "core", name: "@cc-discord-framework/core", dir: repoRoot },
	{
		id: "utils",
		name: "@cc-discord-framework/utils",
		dir: path.join(repoRoot, "plugins", "utils"),
		// ThemeOptions が参照する内部型(意図的に非公開)。
		extraArgs: ["--intentionallyNotExported", "DeepPartial"],
	},
	{ id: "music", name: "@cc-discord-framework/music", dir: path.join(repoRoot, "plugins", "music") },
	{
		id: "music-sources",
		name: "@cc-discord-framework/music-sources",
		dir: path.join(repoRoot, "plugins", "music-sources"),
	},
	{ id: "ai", name: "@cc-discord-framework/ai", dir: path.join(repoRoot, "plugins", "ai") },
] as const;

function runTypedoc(args: string[]): void {
	const result = spawnSync(typedocBin, args, { stdio: "inherit", cwd: websiteDir });
	if (result.status !== 0) {
		throw new Error(`typedoc failed (exit code ${result.status}): typedoc ${args.join(" ")}`);
	}
}

// 1. パッケージごとに JSON へ変換
mkdirSync(cacheDir, { recursive: true });
for (const pkg of packages) {
	console.log(`\n--- converting ${pkg.name} ---`);
	runTypedoc([
		"--options",
		path.join(here, "typedoc.base.json"),
		"--entryPoints",
		path.join(pkg.dir, "src", "index.ts"),
		"--tsconfig",
		path.join(pkg.dir, "tsconfig.json"),
		"--name",
		pkg.name,
		"--json",
		path.join(cacheDir, `${pkg.id}.json`),
		...("extraArgs" in pkg ? pkg.extraArgs : []),
	]);
}

// 2. 統合して Markdown を出力(docs/api/ は cleanOutputDir で毎回作り直し)
console.log("\n--- merging & rendering markdown ---");
runTypedoc(["--options", path.join(here, "typedoc.json")]);

// 3. Docusaurus 向け後処理 -------------------------------------------------

// 3-1. HTML アンカー(useHTMLAnchors)を Docusaurus の明示的見出し ID
// (`### 見出し \{#id}`)へ変換する。見出しが日本語のため、TypeDoc の
// リンク先アンカー(#constructor など)と Docusaurus が見出しから生成する
// スラッグが一致せず、そのままでは onBrokenAnchors に引っかかる。
// このサイトは future.v4(mdx1Compat.headingIds 無効)のため、MDX が
// `{` を式と解釈しないよう `\{#id}` とエスケープして書く
// (@docusaurus/utils の escapeMarkdownHeadingIds と同じ形)。
function convertAnchors(dir: string): void {
	for (const entry of readdirSync(dir)) {
		const abs = path.join(dir, entry);
		if (statSync(abs).isDirectory()) {
			convertAnchors(abs);
			continue;
		}
		if (!entry.endsWith(".md")) continue;
		const source = readFileSync(abs, "utf8");
		const converted = source.replace(
			/^<a id="([^"]+)"><\/a>\n\n(#{1,6} .+)$/gm,
			(_, id: string, headingLine: string) => `${headingLine} \\{#${id}}`,
		);
		if (converted !== source) writeFileSync(abs, converted);
	}
}
convertAnchors(outDir);

/** サイドバー上のカテゴリ表示と並び順。 */
const categoryLabels = new Map<string, { label: string; position: number }>(
	packages.map((pkg, index) => [
		// typedoc-plugin-markdown はモジュール名をそのままディレクトリにする
		// (`@cc-discord-framework/utils` → `@cc-discord-framework/utils/`)。
		// 全パッケージが `@cc-discord-framework` スコープのカテゴリ配下に
		// 並ぶため、ラベルはスコープを外した短縮名にする(core / utils / …)。
		pkg.name,
		{ label: pkg.name.split("/").pop() ?? pkg.name, position: index + 2 },
	]),
);

/** シンボル種別ディレクトリの日本語ラベルと並び順。 */
const kindLabels = new Map<string, { label: string; position: number }>([
	["classes", { label: "クラス", position: 1 }],
	["interfaces", { label: "インターフェイス", position: 2 }],
	["type-aliases", { label: "型エイリアス", position: 3 }],
	["enumerations", { label: "列挙型", position: 4 }],
	["functions", { label: "関数", position: 5 }],
	["variables", { label: "変数", position: 6 }],
	["namespaces", { label: "名前空間", position: 7 }],
]);

function writeCategory(dir: string, label: string, position: number, indexDoc?: string): void {
	const category: Record<string, unknown> = { label, position, collapsed: true };
	if (indexDoc !== undefined) {
		category["link"] = { type: "doc", id: indexDoc };
	}
	writeFileSync(path.join(dir, "_category_.json"), `${JSON.stringify(category, null, "\t")}\n`);
}

function docIdFor(fileAbs: string): string {
	// docs/api/foo/index.md → api/foo/index(Docusaurus のドキュメント ID)
	const rel = path.relative(path.join(websiteDir, "docs"), fileAbs);
	return rel.replace(/\.mdx?$/, "");
}

function walk(dir: string, depth: number): void {
	for (const entry of readdirSync(dir)) {
		const abs = path.join(dir, entry);
		if (!statSync(abs).isDirectory()) continue;

		if (depth === 0) {
			// パッケージディレクトリ(スコープ付きは `@cc-discord-framework/` が
			// 1 階層挟まるため、そこは素通しでさらに下を見る)
			const nameFromPath = path.relative(outDir, abs).split(path.sep).join("/");
			const meta = categoryLabels.get(nameFromPath);
			if (meta) {
				const indexFile = path.join(abs, "index.md");
				writeCategory(
					abs,
					meta.label,
					meta.position,
					existsSync(indexFile) ? docIdFor(indexFile) : undefined,
				);
				walk(abs, 2);
			} else {
				// スコープディレクトリ(@cc-discord-framework)
				writeCategory(abs, entry, 3);
				walk(abs, 1);
			}
			continue;
		}

		if (depth === 1) {
			// スコープ配下のパッケージディレクトリ
			const nameFromPath = path.relative(outDir, abs).split(path.sep).join("/");
			const meta = categoryLabels.get(nameFromPath);
			if (meta) {
				const indexFile = path.join(abs, "index.md");
				writeCategory(
					abs,
					meta.label,
					meta.position,
					existsSync(indexFile) ? docIdFor(indexFile) : undefined,
				);
			}
			walk(abs, 2);
			continue;
		}

		// シンボル種別ディレクトリ(classes / interfaces / …)
		const kind = kindLabels.get(entry);
		if (kind) {
			writeCategory(abs, kind.label, kind.position);
		}
		walk(abs, depth + 1);
	}
}

walk(outDir, 0);

// ルートの index.md に frontmatter を付与(サイドバー先頭に固定)
const rootIndex = path.join(outDir, "index.md");
const rootContent = readFileSync(rootIndex, "utf8");
if (!rootContent.startsWith("---\n")) {
	writeFileSync(rootIndex, `---\nsidebar_position: 1\n---\n\n${rootContent}`);
}

console.log(`\nAPI リファレンスを生成しました: ${outDir}`);
