import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * サイドバーは3系統に分かれます。
 *
 * - docs:    フレームワーク利用者向けドキュメント(導入・ガイド)
 * - plugins: 公式プラグインの利用者向けドキュメント
 * - api:     公開 API リファレンス(TypeDoc から生成)
 *
 * `docs/` 配下のディレクトリ構成から自動生成します — ファイルを置けば
 * サイドバーに載ります(順序は各ディレクトリの _category_.json と
 * frontmatter の sidebar_position で制御)。
 */
const sidebars: SidebarsConfig = {
	docs: [{ type: "autogenerated", dirName: "framework" }],
	plugins: [{ type: "autogenerated", dirName: "plugins" }],
	api: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
